### PR TITLE
fixed Soudan grid, added email form and footer

### PR DESCRIPTION
**Pull request by phann-phearoen**

### CODE REVIEW

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Thank you for hard working!

I pulled your branch and run dev server.
it is good on overall layout and actions by responsiveness.

but,  there are two things that I want you to take care of

Screen Shot 2021-07-12 at 15 43 05

1.  Please fill out image on full-width area as a background.
2.  The font size is too small. it is better to make them bigger. Also, buttons are not working now. Please add auto-scroll functions to locate correct positions when they are clicked.


Thanks!

**Comment by phann-phearoen** [comment]
Got it!

That's all I wanted!
1. My laptop resolution is small that's why I never saw this bug.
2. I'll implement this function once I finished working with all elements.

Thank you so much!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Hi, Phann.
How is about your progress for issues stated below?

```
1. Please fill out image on full-width area as a background.
2. The font size is too small. it is better to make them bigger. Also, buttons are not working now. Please add auto-scroll functions to locate correct positions when they are clicked.
```

Your solution for the above issues are committed to final_part PR??
If so, I am gonna merge this branch. Please confirm this PR and let me know. :)

**Comment by phann-phearoen** [comment]
It's all done, but the branch is not that one.
I'm pushing a new branch called 'complete'.
Please merge this one, and please be informed that the Website is now
primarily complete.
Please check it out for further modifications.
Thank you!

**Pull request merged**
